/**
 * Historical git log backfill for Gyst.
 *
 * Where `git-hook.ts` captures new commits as they happen, this module
 * walks a project's existing git history and replays each commit through
 * the same capture path. That lets a user run `gyst backfill` once on a
 * mature repository and immediately populate the knowledge base with
 * years of decisions, fixes, and refactors — dedup is handled by the
 * shared `addManualEntry` pipeline.
 *
 * Filters:
 *   - `since`   : git ref, SHA, or date accepted by `git log --since=`
 *   - `author`  : substring / regex applied to author name + email
 *   - `paths`   : limit to commits that touched any of these paths
 *   - `max`     : hard cap on commits scanned (default 500)
 *   - `dryRun`  : report what would be written without touching the DB
 */

import type { Database } from "bun:sqlite";
import parseGitDiff from "parse-git-diff";
import simpleGit, { type SimpleGit } from "simple-git";
import { addManualEntry } from "./manual.js";
import type { EntryType } from "./manual.js";
import { stripSensitiveData } from "../compiler/security.js";
import { logger } from "../utils/logger.js";

/** Markers that a commit was AI-authored (mirrors git-hook.ts). */
const AI_MARKERS: readonly string[] = [
  "co-authored-by: claude",
  "co-authored-by: cursor",
  "co-authored-by: copilot",
  "co-authored-by: github copilot",
  "🤖",
  "aider:",
  "[ai]",
  "generated by",
];

/** Commits below this combined line count are only captured if they
 *  are AI-authored or match a Conventional Commits prefix. */
const SIGNIFICANT_CHANGE_THRESHOLD = 50;

export interface BackfillOptions {
  readonly since?: string;
  readonly author?: string;
  readonly paths?: readonly string[];
  readonly max?: number;
  readonly dryRun?: boolean;
}

export interface BackfillReport {
  readonly scanned: number;
  readonly captured: number;
  readonly skipped: number;
  readonly failed: number;
}

interface RawCommit {
  readonly hash: string;
  readonly author_name: string;
  readonly author_email: string;
  readonly date: string;
  readonly message: string;
}

/**
 * Walks the git history of `workingDir` and captures each qualifying
 * commit into the knowledge base via `addManualEntry`.
 *
 * Returns counts, never throws: per-commit failures are logged and
 * counted so a single bad commit can't abort a long backfill.
 *
 * @param db      - Open database connection (caller owns lifecycle).
 * @param opts    - Filters for the walk.
 * @param workingDir - Repo root. Defaults to `process.cwd()`.
 */
export async function backfillCommits(
  db: Database,
  opts: BackfillOptions = {},
  workingDir: string = process.cwd(),
): Promise<BackfillReport> {
  const git: SimpleGit = simpleGit(workingDir);

  // Fail fast when we're not inside a git repo — a friendlier error
  // than simple-git's cryptic "fatal: not a git repository" throw.
  let insideRepo = false;
  try {
    insideRepo = await git.checkIsRepo();
  } catch {
    insideRepo = false;
  }
  if (!insideRepo) {
    logger.warn("backfill: not a git repository", { workingDir });
    return { scanned: 0, captured: 0, skipped: 0, failed: 0 };
  }

  const max = opts.max ?? 500;
  const commits = await listCommits(git, opts, max);

  let captured = 0;
  let skipped = 0;
  let failed = 0;

  for (const commit of commits) {
    try {
      const outcome = await processCommit(db, git, commit, opts.dryRun ?? false);
      if (outcome === "captured") captured += 1;
      else if (outcome === "skipped") skipped += 1;
    } catch (err) {
      failed += 1;
      const msg = err instanceof Error ? err.message : String(err);
      logger.warn("backfill: commit failed", { hash: commit.hash, error: msg });
    }
  }

  logger.info("backfill: complete", {
    scanned: commits.length,
    captured,
    skipped,
    failed,
  });

  return { scanned: commits.length, captured, skipped, failed };
}

/**
 * Lists commits that match the caller's filters. `simple-git.log`
 * accepts both `--author` and pathspec arguments, so both filters
 * are passed directly to git and don't need a client-side pass.
 */
async function listCommits(
  git: SimpleGit,
  opts: BackfillOptions,
  max: number,
): Promise<RawCommit[]> {
  const args: string[] = [`--max-count=${max}`];
  if (opts.since) args.push(`--since=${opts.since}`);
  if (opts.author) args.push(`--author=${opts.author}`);

  // `--` separates revision args from pathspecs. simple-git passes the
  // array through verbatim, so this is the same shape git itself expects.
  const paths = opts.paths?.filter((p) => p.trim().length > 0) ?? [];
  if (paths.length > 0) {
    args.push("--");
    for (const p of paths) args.push(p);
  }

  const log = await git.log(args);
  return log.all.map((c) => ({
    hash: c.hash,
    author_name: c.author_name,
    author_email: c.author_email,
    date: c.date,
    message: c.message + (c.body ? `\n\n${c.body}` : ""),
  }));
}

/**
 * Decides whether a single commit is worth capturing and — if so — writes
 * it through the manual-entry pipeline. Returns a tag so the caller can
 * tally outcomes without a second pass.
 */
async function processCommit(
  db: Database,
  git: SimpleGit,
  commit: RawCommit,
  dryRun: boolean,
): Promise<"captured" | "skipped"> {
  const parsed = parseConventional(commit.message);
  const isAiAuthored = AI_MARKERS.some((m) =>
    commit.message.toLowerCase().includes(m),
  );

  const diff = await safeDiffSummary(git, commit.hash);
  const totalLinesChanged = diff.insertions + diff.deletions;
  const isSignificant = totalLinesChanged >= SIGNIFICANT_CHANGE_THRESHOLD;

  if (!parsed && !isAiAuthored && !isSignificant) {
    return "skipped";
  }

  const changedFiles = diff.files;
  const entryType: EntryType = parsed?.type ?? "learning";
  const safeMessage = stripSensitiveData(commit.message);
  const title =
    parsed?.title ?? (safeMessage.split("\n")[0]?.trim() || commit.hash.slice(0, 7));

  const tags: string[] = ["backfill"];
  if (parsed) tags.push(`commit:${entryType}`);
  if (isAiAuthored) tags.push("ai-authored");
  if (!parsed && isSignificant) tags.push("significant-change");

  const content = [
    `Commit: ${commit.hash}`,
    `Author: ${commit.author_name} <${commit.author_email}>`,
    `Date: ${commit.date}`,
    "",
    safeMessage,
    "",
    `Changed files (${changedFiles.length}): ${changedFiles.join(", ")}`,
    `Insertions: ${diff.insertions}  Deletions: ${diff.deletions}`,
    isAiAuthored ? "\n[AI-authored commit]" : "",
  ]
    .join("\n")
    .trim();

  if (dryRun) {
    process.stdout.write(
      `  [dry] ${commit.hash.slice(0, 7)}  ${entryType.padEnd(14)}  ${title}\n`,
    );
    return "captured";
  }

  await addManualEntry(db, {
    type: entryType,
    title,
    content,
    files: changedFiles,
    tags,
  });

  return "captured";
}

/**
 * Conventional Commits parser. Shared with `src/compiler/parsers/commit.ts`
 * in spirit but reimplemented against an arbitrary message string so we
 * can parse historical commits without round-tripping through git twice.
 */
function parseConventional(
  message: string,
): { type: EntryType; title: string } | null {
  const match = message.match(/^(\w+)(?:\(([^)]+)\))?\s*:\s*(.*)/);
  if (!match) return null;

  const [, type, scope, subject] = match;
  let title = (subject ?? "").trim();
  if (!title) return null;
  if (scope) title = `${scope}: ${title}`;

  let entryType: EntryType = "learning";
  if (type === "fix") {
    entryType = "error_pattern";
    if (!title.toLowerCase().startsWith("fix")) title = `Fix: ${title}`;
  } else if (type === "feat" || type === "refactor") {
    entryType = "decision";
  }

  return { type: entryType, title };
}

interface DiffSummary {
  readonly files: string[];
  readonly insertions: number;
  readonly deletions: number;
}

/**
 * Pulls a per-commit diff summary without exploding on the initial commit
 * (which has no parent). simple-git's `diffSummary` throws for `HASH~1`
 * when the hash is a root commit, so we fall back to an empty summary.
 */
async function safeDiffSummary(
  git: SimpleGit,
  hash: string,
): Promise<DiffSummary> {
  try {
    const show = await git.show([
      "--unified=0",
      "--pretty=format:",
      hash,
    ]);
    const parsed = parseGitDiff(show);
    const files: string[] = [];
    let insertions = 0;
    let deletions = 0;
    for (const f of parsed.files) {
      if ("path" in f && f.path) files.push(f.path);
      for (const chunk of f.chunks) {
        if (!("changes" in chunk)) continue;
        for (const c of chunk.changes) {
          if (c.type === "AddedLine") insertions += 1;
          else if (c.type === "DeletedLine") deletions += 1;
        }
      }
    }
    return { files, insertions, deletions };
  } catch {
    return { files: [], insertions: 0, deletions: 0 };
  }
}
