/**
 * Post-commit hook handler for Gyst.
 *
 * Invoked by the installed git post-commit hook after every commit.
 * Captures commit metadata and stores AI-authored or significant commits
 * as learning entries in the knowledge base.
 *
 * This module MUST NOT fail the commit — all errors are caught and logged,
 * and the process exits with code 0 regardless.
 */

import simpleGit from "simple-git";
import { initDatabase } from "../store/database.js";
import { logger } from "../utils/logger.js";
import { stripSensitiveData } from "../compiler/security.js";
import { loadConfig } from "../utils/config.js";

// ---------------------------------------------------------------------------
// AI authorship detection
// ---------------------------------------------------------------------------

const AI_MARKERS = [
  "co-authored-by: claude",
  "co-authored-by: cursor",
  "co-authored-by: copilot",
  "co-authored-by: github copilot",
  "🤖",
  "aider:",
  "[ai]",
  "generated by",
] as const;

/**
 * Checks whether a commit message contains known AI authorship markers.
 *
 * @param message - The raw commit message to inspect.
 * @returns `true` if at least one marker is detected (case-insensitive).
 */
function detectAiAuthorship(message: string): boolean {
  const lower = message.toLowerCase();
  return AI_MARKERS.some((marker) => lower.includes(marker.toLowerCase()));
}

// ---------------------------------------------------------------------------
// Significance threshold
// ---------------------------------------------------------------------------

/** Minimum combined line change count to consider a non-AI commit significant. */
const SIGNIFICANT_CHANGE_THRESHOLD = 50;

// ---------------------------------------------------------------------------
// captureCommit
// ---------------------------------------------------------------------------

/**
 * Captures the latest commit's metadata and stores it as a learning entry
 * when the commit is AI-authored or exceeds the significance threshold.
 *
 * Called by the installed git post-commit hook script. Errors are swallowed
 * so the commit is never blocked.
 */
export async function captureCommit(): Promise<void> {
  const git = simpleGit();

  // 1. Get the latest commit details
  const log = await git.log({ maxCount: 1 });
  const latest = log.latest;
  if (!latest) {
    logger.debug("captureCommit: no latest commit found — skipping");
    return;
  }

  // 2. Get the diff summary (files changed, insertions, deletions)
  let diff;
  try {
    diff = await git.diffSummary(["HEAD~1", "HEAD"]);
  } catch {
    // First commit has no HEAD~1; treat diff as empty
    diff = { changed: 0, insertions: 0, deletions: 0, files: [] };
  }

  // 3. Check for AI authorship markers in commit message
  const isAiAuthored = detectAiAuthorship(latest.message);
  const totalLinesChanged = diff.insertions + diff.deletions;
  const isSignificant = totalLinesChanged >= SIGNIFICANT_CHANGE_THRESHOLD;

  if (!isAiAuthored && !isSignificant) {
    logger.debug("captureCommit: commit not AI-authored and not significant — skipping", {
      hash: latest.hash,
      totalLinesChanged,
    });
    return;
  }

  // 4. Strip sensitive data from commit message
  const safeMessage = stripSensitiveData(latest.message);

  // 5. Derive affected file paths from diff summary
  const changedFiles = diff.files.map((f) => f.file);

  // 6. Store in database as a learning entry
  const config = loadConfig();
  const db = await initDatabase(config.dbPath);

  try {
    const { addManualEntry } = await import("../capture/manual.js");

    const title = safeMessage.split("\n")[0]?.trim() ?? latest.hash;
    const content = [
      `Commit: ${latest.hash}`,
      `Author: ${latest.author_name}`,
      `Date: ${latest.date}`,
      "",
      safeMessage,
      "",
      `Changed files (${diff.changed}): ${changedFiles.join(", ")}`,
      `Insertions: ${diff.insertions}  Deletions: ${diff.deletions}`,
      isAiAuthored ? "\n[AI-authored commit]" : "",
    ]
      .join("\n")
      .trim();

    const entryId = await addManualEntry(db, {
      type: "learning",
      title,
      content,
      files: changedFiles,
      tags: isAiAuthored ? ["ai-authored"] : ["significant-change"],
    });

    logger.info("captureCommit: entry stored", {
      entryId,
      hash: latest.hash,
      isAiAuthored,
      totalLinesChanged,
    });
  } finally {
    db.close();
  }
}

// ---------------------------------------------------------------------------
// CLI entry point
// ---------------------------------------------------------------------------

if (import.meta.main) {
  captureCommit().catch((err: unknown) => {
    const message = err instanceof Error ? err.message : String(err);
    logger.error("Failed to capture commit", { error: message });
    // Never block the commit — always exit 0
    process.exit(0);
  });
}
